# action.yml
---
name: 'FX Data Download Action'
description: 'Downloads Forex historical data'
author: 'kenorb'
inputs:

  Pairs:
    description: 'Pairs to download'
    default: 'EURUSD'

  Years:
    description: 'Years to download'
    default: 2020
  Months:
    description: 'Months to download'
    default: 1
  Days:
    description: 'Days to download'
    default: 1
  Hours:
    description: 'Hours to download'
    default: 'all'

# outputs:
#  foo: # id of output
#    description: 'Foo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:

    - '-p'
    - '${{ inputs.Pairs }}'

    - '-y'
    - '${{ inputs.Years }}'
    - '-m'
    - '${{ inputs.Months }}'
    - '-d'
    - '${{ inputs.Days }}'
    - '-h'
    - '${{ inputs.Hours }}'

branding:
  icon: 'bar-chart'
  color: 'green'
